### ISSUE TITLE
libraries for hyperparameter handling

### ISSUE THREAD

**Issue by rmminusrslash** [EthicalML/awesome-production-machine-learning#105]
In a training pipelines, we sometimes get tripped by how to best handle and pass around the 5gazillion hyperparameters of data preparation and training. There are some libraries that focus on good configuration for ML:

https://github.com/google/gin-config
https://github.com/PetrochukM/HParams

Is this topic too specific? If not where could it go?

**Comment by axsaucedo** [comment]
Interesting find -not too specifica at all! The section in the list relevant for hyperparameter search would be https://github.com/EthicalML/awesome-production-machine-learning#feature-engineering-automation.
