### ISSUE TITLE
Where to add CML?

### ISSUE THREAD

**Issue by gleydson404** [EthicalML/awesome-production-machine-learning#106]
Creators of DVC released today https://github.com/iterative/cml

What is the recommended place to put this lib?

**Comment by axsaucedo** [comment]
Yes! Nice shout, the features are mostly on the training, and even though it does encompass some deployment related features it's definitely not a serving / orchestration framework so most suitable section is Model Training Orchestration. @gleydson404 would you be able to open a PR?

**Comment by gleydson404** [comment]
Thanks for answering @axsaucedo. Yes, sure, I will open a PR adding CML.

**Comment by axsaucedo** [comment]
Thanks @gleydson404 !
