### ISSUE TITLE
Amazing list! can we add Haven (https://github.com/ElementAI/haven) as well? 

### ISSUE THREAD

**Issue by IssamLaradji** [EthicalML/awesome-production-machine-learning#110]
Thanks for creating an amazing list that help people setup a productive workflow.

Would it be possible to add Haven (https://github.com/ElementAI/haven) to the list?

The goal of Haven is to help in running, managing, visualizing, and sharing a large number of experiments in parallel.

Thanks!

**Comment by axsaucedo** [comment]
Closing as inactive
