### ISSUE TITLE
Section for ML standards?

### ISSUE THREAD

**Issue by fkromer** [EthicalML/awesome-production-machine-learning#121]
Do we want to add a section for standards w.r.t. the development of ML models? One standard is e.g. [DIN SPEC 92001-1](https://www.beuth.de/de/technische-regel/din-spec-92001-1/303650673).

**Comment by axsaucedo** [comment]
Interesting @fkromer , I have been thinking whether adding extra section on things like standards. Currently the list has primarily a focus on frameworks, but there could be scope in the future to add sections on things like tutorials, standards, artciles, etc. For the meantime we actually have another list where this could actually fit quite well - namely https://github.com/EthicalML/awesome-artificial-intelligence-guidelines. Would you be able to add it to that one for now?
