### ISSUE TITLE
Labeling of time series data

### ISSUE THREAD

**Issue by fkromer** [EthicalML/awesome-production-machine-learning#126]
There is [trainset](https://github.com/geocene/trainset) for lightweight UI-based visual labeling of time series data. Does someone know standalone tool alternative to trainset?

BTW: Grafana provides [annotation API](https://grafana.com/docs/grafana/latest/http_api/annotations/) but I don't know an UI integration/tool which enable "drag & drop" style usage.

**Comment by axsaucedo** [comment]
Interesting! The area of data labelling for time series is less covered, I think it would be great to add trainset into the data labelling section. The annotation API of grafana looks interesting as well, although given it's not an independent library by itself I don't think we could add it for now. Woudl you be up for adding an extra PR for the trainset library @fkromer ?
