### ISSUE TITLE
Adding Haven-Ai to the curated list

### ISSUE THREAD

**Issue by IssamLaradji** [EthicalML/awesome-production-machine-learning#143]
Thanks for curating a list of useful libraries that help people deploy machine learning projects!

Would it be okay to add the `Haven-Ai` library to the list? https://github.com/haven-ai/haven-ai 

It's a library that we have been working on over the last 3 years that allows us to design codebase for quick reliable prototyping and also  running, managing and visualizing large scale reproducible experiments. 

I think it fits under `Model and Data Versioning` section in the README.md. 

Thanks a lot!

**Comment by axsaucedo** [comment]
Closing as inactive
