### ISSUE TITLE
Add section on metadata stores

### ISSUE THREAD

**Issue by axsaucedo** [EthicalML/awesome-production-machine-learning#146]

**Comment by visenger** [comment]
jepp! [ML Metadata (MLMD)](https://github.com/google/ml-metadata) is a first candidate for this section :)

**Comment by axsaucedo** [comment]
@visenger  Thank you! Yes, it seems 2020 is the year of metadata stores - from mind some others are:
* Amundsen
* Linkedin DataHub
* Apache Atlas

I do have to say that I've been putting off this section primarily as previously tools have tended towards adding metadata as one of several features, but I guess they could now be moved to the metadata section - these include:
* ModelDB
* MLFlow

**Comment by visenger** [comment]
Here we go with other metadata systems:

- DataHub (LinkedIn): https://github.com/linkedin/datahub https://engineering.linkedin.com/blog/2019/data-hub
- Dataportal (Airbnb): https://medium.com/airbnb-engineering/democratizing-data-at-airbnb-852d76c51770
- Metacat (Netflix): https://github.com/Netflix/metacat https://netflixtechblog.com/metacat-making-big-data-discoverable-and-meaningful-at-netflix-56fb36a53520?gi=ddd96f380ab4
- Amundsen (Lyft): https://lyft.github.io/amundsen/  https://eng.lyft.com/amundsen-lyfts-data-discovery-metadata-engine-62d27254fbb9?gi=e5a89935d462
- Databook (Uber): https://eng.uber.com/databook/
- Data Catalog (Google): https://cloud.google.com/data-catalog/
- Apache Atlas - Data Governance and Metadata framework for Hadoop: https://atlas.apache.org/#/
- Marquez - Collect, aggregate, and visualize a data ecosystem's metadata https://marquezproject.github.io/marquez/
- great_expectations: https://github.com/great-expectations/great_expectations

**Comment by axsaucedo** [comment]
Aweosme @visenger ! This is fantastic, would you be interested on doing a PR? If you're busy no worries, I'll be able to add these this weekedn as well 🙂

**Comment by visenger** [comment]
yeah, @axsaucedo , go ahead! Thank you! 👍
