### ISSUE TITLE
Add labelling tools

### ISSUE THREAD

**Issue by fabraz** [EthicalML/awesome-production-machine-learning#170]
The following tools are more appropriate for NLP
[INCEpTION](https://inception-project.github.io/)
[Webanno](https://webanno.github.io/)
[TeamTat](https://github.com/ncbi-nlp/TeamTat)

**Comment by axsaucedo** [comment]
This is great suggestion, could you add a pr?

**Comment by axsaucedo** [comment]
Closing as inactive
