### ISSUE TITLE
Add online experimentation engine section

### ISSUE THREAD

**Issue by hardianlawi** [EthicalML/awesome-production-machine-learning#196]
Hi,

Could we add a section to list the open-source tools available to design or run online experiments?

Some examples

- https://github.com/facebook/planout
- https://github.com/gojek/turing

Thank you!

**Comment by axsaucedo** [comment]
Both look reasonable projects to add - could you add them in a PR?

**Comment by hardianlawi** [comment]
I have created a PR https://github.com/EthicalML/awesome-production-machine-learning/pull/197. Please review! Thank you!
