### ISSUE TITLE
A mistake in headers ("Data Storage Layer" vs "Data Storage Optimisation")?

### ISSUE THREAD

**Issue by bobvanluijt** [EthicalML/awesome-production-machine-learning#209]
In the [overview section](https://github.com/EthicalML/awesome-production-machine-learning/tree/weaviate-with-new-section#quick-links-to-sections-in-this-page) it states "Data Storage Layer" this makes sense looking at what is in there. But the [section itself](https://github.com/EthicalML/awesome-production-machine-learning#data-storage-optimisation) is called "Data Storage Optimisation". Shouldn't this also be "Data Storage Layer"?

**Comment by axsaucedo** [comment]
Good shout, thanks for the heads up - I have updated now

**Comment by bobvanluijt** [comment]
You're welcome :)
