### ISSUE TITLE
Suggestion: add "Vector Database" section

### ISSUE THREAD

**Issue by bobvanluijt** [EthicalML/awesome-production-machine-learning#212]
Vector databases are a relatively new phenomenon, but they might deserve their own section.

For the convenience of the maintainer of this repo, I've added two PRs, one [without the new section](https://github.com/EthicalML/awesome-production-machine-learning/pull/211) one [with the new section](https://github.com/EthicalML/awesome-production-machine-learning/pull/210).

This reading material about [Weaviate]() might be helpful in the argumentation why the vector database might deserve its own spot on this list :)

- https://db-engines.com/en/blog_post/87
- https://www.zdnet.com/article/weaviate-an-open-source-search-engine-powered-by-machine-learning-vectors-graphs-and-graphql/

**Comment by axsaucedo** [comment]
This seems interesting but as per CONTRIBUTING.md guidelines 5-10 projects have to be identified, for the time being adding thees to the existing sections is best. Closing but can re-explore if 5-10 can be proposed
