### ISSUE TITLE
Suggestions: Added Pandas Profile for EDA

### ISSUE THREAD

**Issue by tamersalama** [EthicalML/awesome-production-machine-learning#231]
A very good tool for EDA

https://github.com/pandas-profiling/pandas-profiling

I can issue a pull request if decided.

**Comment by axsaucedo** [comment]
Looks interesting and relevant - a pr would be certainly appreciated

**Comment by tamersalama** [comment]
Created pull request #235

**Comment by axsaucedo** [comment]
merged so closing
