### ISSUE TITLE
Suggestion: Add Ploomber for Model Training Orchestration

### ISSUE THREAD

**Issue by reesehopkins** [EthicalML/awesome-production-machine-learning#261]
I've been using [ploomber](https://github.com/ploomber/ploomber/) for model training, orchestration. It's helped keep my work reproducible. Would you accept a PR for this?

**Comment by axsaucedo** [comment]
This looks great @reesehopkins , seems relevant - would you be able to add a PR? you can read the guidelines in CONTRIBUTING.md
