### ISSUE TITLE
Add TDengine (https://github.com/taosdata) to Data Storage Optimisation as a time-series platform

### ISSUE THREAD

**Issue by cdiwadkar16** [EthicalML/awesome-production-machine-learning#274]
TDengine is an open source time-series database and has more than 19K stars on Github.

**Comment by axsaucedo** [comment]
Seems interesting @cdiwadkar16 - would you be able to add a PR? You can ready the CONTRIBUTING.md for instructions

**Comment by axsaucedo** [comment]
Closing as aligned but do add a pr if possible
