### ISSUE TITLE
invalid description for gglplot2 

### ISSUE THREAD

**Issue by kdubovikov** [EthicalML/awesome-production-machine-learning#30]
The description for ggplot2 mentions that it is a Python library, but it is an R library.

**Comment by axsaucedo** [comment]
Thank you for th heads up @kdubovikov . Would you be able to submit a PR for the fix?

**Comment by kdubovikov** [comment]
@axsaucedo, glad to help. Here you go: https://github.com/EthicalML/awesome-production-machine-learning/pull/32

**Comment by axsaucedo** [comment]
Thank you for your contribution @kdubovikov !
