### ISSUE TITLE
Please add fiftyone and ymir

### ISSUE THREAD

**Issue by zhanglazhuan** [EthicalML/awesome-production-machine-learning#304]
1. https://voxel51.com/docs/fiftyone/
2. https://github.com/IndustryEssentials/ymir

**Comment by axsaucedo** [comment]
These look good @zhanglazhuan - are you able to open a PR? You can read about the steps in the CONTRIBUTING.md

**Comment by axsaucedo** [comment]
Closing as aligned but do add a pr if possible
