### ISSUE TITLE
Nebullvm or Speedster

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#309]
Since Speedster is already a part of Nebullvm, why not integrate Speedster into Nebullvm?  @axsaucedo 
The logic is straightforward. We only keep Ray rather than its specific component such as Rllib (a famous production-level reinforcement learning library). 

* [Nebullvm](https://github.com/nebuly-ai/nebullvm) ![](https://img.shields.io/github/stars/nebuly-ai/nebullvm.svg?style=social) - Nebullvm is an ecosystem of plug-and-play modules to boost the performances of your AI systems. The optimization modules are stack-agnostic and work with any library. They are designed to be easily integrated into your system, providing a quick and seamless boost to its performance.

Would you mind reopening this pr for further discussion? https://github.com/EthicalML/awesome-production-machine-learning/pull/307

**Comment by axsaucedo** [comment]
Sounds good @zhimin-z ,thsnk you for driving forward the discussion, I have reopened the pr for discussion

**Comment by zhimin-z** [comment]
https://github.com/EthicalML/awesome-production-machine-learning/pull/312
