### ISSUE TITLE
Suggestion: Add tournesol.app platform

### ISSUE THREAD

**Issue by aidanjungo** [EthicalML/awesome-production-machine-learning#310]
[Tournesol](tournesol.app) is a collaborative content recommendation platform based on the latest research in AI security (some articles on the algorithms used have already been published). The goal of Tournesol is to identify top videos of public utility by eliciting contributors' judgements on content quality. All the code is open-source and available here https://github.com/tournesol-app/tournesol

If the suggestion is accepted, I may do a PR.

**Comment by axsaucedo** [comment]
This doesn't seem to be an application to productionise ML so unfortunately at this stage it wouldn't be relevant for this list
