### ISSUE TITLE
Shall we open section for domain-specific ML application?

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#319]
For example, **Industry-strength Finance** such as [Qlib](https://github.com/microsoft/qlib)? **Industry-strength Healthcare** such as [MONAI](https://github.com/Project-MONAI/MONAI), [torchxrayvision](https://github.com/mlmed/torchxrayvision), [hi-ml](https://github.com/microsoft/hi-ml), [InnerEye](https://www.microsoft.com/en-us/research/project/medical-image-analysis), [STORM](https://github.com/stanford-oval/storm)? @axsaucedo

**Comment by axsaucedo** [comment]
This was discussed as well in the recent proposal to add RecSys sections, domain specific sections at this stage I'm not really sure (as could also explore Fraud detection, recommender systems, etc). However for most cases these frameworks can fit better in the existing sections. My main thoughss is that for example these latter 3-4 seem to fit well in the CV section.

Having said that, it does sound interesting. Especially the healthcare as you did find 3 (not sure about the last one whether OSS). I will update the CONTRIBUTING.md to have 5 as the min for a section, but I think if we can find 5 for these sections that are non-ambiguously supposed to fit on other sections it does seem like an idea with potential.

I would say for now let's add them in the respective sections (i.e. in Image CV) and then if we see a pattern where we can break up a section in to respective domain specific ones we can explore further.

**Comment by al-yakubovich** [comment]
Hi [axsaucedo](https://github.com/axsaucedo) and [zhimin-z](https://github.com/zhimin-z). I just want to give some updates regarding the RecSys section. Here is the list of frameworks that could potentially be included in such a section. 

1. [NVIDIA Merlin](https://github.com/NVIDIA-Merlin/Merlin)
2. [Surprise](https://github.com/nicolashug/surprise)
3. [LightFM](https://github.com/lyst/lightfm)
4. [Microsoft Recommenders](https://github.com/Microsoft/Recommenders)
5. [Implicit](https://github.com/benfred/implicit)
6. [EasyRec](https://github.com/alibaba/EasyRec)
7. [ProbQA](https://github.com/srogatch/ProbQA)
8. [Gorse](https://github.com/gorse-io/gorse)
9. [QMF](https://github.com/quora/qmf)

**Comment by zhimin-z** [comment]
> Hi [axsaucedo](https://github.com/axsaucedo) and [zhimin-z](https://github.com/zhimin-z). I just want to give some updates regarding the RecSys section. Here is the list of frameworks that could potentially be included in such a section. 
> 
> 1. [NVIDIA Merlin](https://github.com/NVIDIA-Merlin/Merlin)
> 2. [Surprise](https://github.com/nicolashug/surprise)
> 3. [LightFM](https://github.com/lyst/lightfm)
> 4. [Microsoft Recommenders](https://github.com/Microsoft/Recommenders)
> 5. [Implicit](https://github.com/benfred/implicit)
> 6. [EasyRec](https://github.com/alibaba/EasyRec)
> 7. [ProbQA](https://github.com/srogatch/ProbQA)
> 8. [Gorse](https://github.com/gorse-io/gorse)
> 9. [QMF](https://github.com/quora/qmf)

@axsaucedo I think this might be promising somehow, any idea?

**Comment by zhimin-z** [comment]
> > Hi [axsaucedo](https://github.com/axsaucedo) and [zhimin-z](https://github.com/zhimin-z). I just want to give some updates regarding the RecSys section. Here is the list of frameworks that could potentially be included in such a section. 
> > 
> > 1. [NVIDIA Merlin](https://github.com/NVIDIA-Merlin/Merlin)
> > 2. [Surprise](https://github.com/nicolashug/surprise)
> > 3. [LightFM](https://github.com/lyst/lightfm)
> > 4. [Microsoft Recommenders](https://github.com/Microsoft/Recommenders)
> > 5. [Implicit](https://github.com/benfred/implicit)
> > 6. [EasyRec](https://github.com/alibaba/EasyRec)
> > 7. [ProbQA](https://github.com/srogatch/ProbQA)
> > 8. [Gorse](https://github.com/gorse-io/gorse)
> > 9. [QMF](https://github.com/quora/qmf)
> 
> Plus [NVTabular](https://github.com/NVIDIA-Merlin/NVTabular). We have at least ten tools to ship in terms of Recommender systems and consider the impact of recommender systems in various ML applications as well as its distinct properties from NLP/CV/RL/Visualization domain, I think this might be promising somehow, maybe we can launch a new application section afterward. @axsaucedo

I have created a pr(https://github.com/EthicalML/awesome-production-machine-learning/pull/364) which includes most of the tools above (QMF and ProbQA are excluded due to insufficient stars and not quite explicitly designed for RecSys). @axsaucedo @al-yakubovich Take a look!

**Comment by axsaucedo** [comment]
+1, I completely agree, this list is great, I am surprised I have not come across these projects before

Only thing is that probqa, recommenders and QMF seem they don't meet ther requirements - other than that seems good addition
