### ISSUE TITLE
Proposition for reopening closed pr

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#320]
Hi, @axsaucedo I found the discussion regarding https://github.com/EthicalML/awesome-production-machine-learning/pull/294 https://github.com/EthicalML/awesome-production-machine-learning/pull/293 is far from ended, I wonder if we can reopen them for further discussion? I appreciate it a lot!

**Comment by axsaucedo** [comment]
As discussed the action will be to create respective issues - thank you @zhimin-z

**Comment by zhimin-z** [comment]
> eate respective issue

I replied to your my rebuttal on respective issues, would you like to give me further feedback? @axsaucedo
