### ISSUE TITLE
Can we publish more latest release?

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#324]
@axsaucedo such as https://github.com/EthicalML/awesome-production-machine-learning/releases. The current one publishes almost two years ago.

**Comment by axsaucedo** [comment]
Absolutely! I was actually looking yesterday at a github action that performs releases every week / month, namely a workflow with:

* Tagging date / week
* Changelog generator
* Convert MD to PDF with pandoc
* Create release
* Attach changelog and PDF to release
* Publish release

It would be great to do this automatically - would this be something you would be interested to explore?

I have been meaning to do this for a while but haven't been able to get around, but it would make such a difference!

Let me know your thoughts

**Comment by axsaucedo** [comment]
Ok I have created #353 in favour to run it based on this proposal - let me know your thoughts
