### ISSUE TITLE
Remove general tools that aim not for model deployment specifically

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#334]
Some tools in the FaaS module are designed to solve more general scalability issues rather than model deployment.
I suggest removing those available tools from our list since they seem misleading somehow. For example, we should not include Kubernetes in our list since it is a general tool that aims not for model deployment specifically.
check https://github.com/EthicalML/awesome-production-machine-learning/pull/333

**Comment by axsaucedo** [comment]
Closing as already carried out
