### ISSUE TITLE
How can we categorize CodaLab

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#335]
https://github.com/codalab/codalab-worksheets/, the famous experiment tracking tool powering HuggingFace, SQUAD, etc.

**Comment by zhimin-z** [comment]
relate to https://github.com/EthicalML/awesome-production-machine-learning/pull/293

**Comment by axsaucedo** [comment]
Good question, there are platforms that tend to have a lot of functionalities, but often trying to take (or choose) the most prominent and add there, i would say for this one in the model and data versioning

**Comment by axsaucedo** [comment]
Closing as aligned on discussion on section

**Comment by zhimin-z** [comment]
> Good question, there are platforms that tend to have a lot of functionalities, but often trying to take (or choose) the most prominent and add there, i would say for this one in the model and data versioning

Hi @axsaucedo But the key issue is that Colab did nothing about model&data versioning if you took a closer look. This is made exclusively for experiment reproducibility. I think we should reconsider my previous proposal related to https://github.com/EthicalML/awesome-production-machine-learning/pull/293

**Comment by axsaucedo** [comment]
Experiment reproducibility = model & data versioning, which is why it's suggested to include in that section

**Comment by zhimin-z** [comment]
> Experiment reproducibility = model & data versioning, which is why it's suggested to include in that section

I do not think this holds: Experiment reproducibility = model & data versioning, honestly.
roughly, we need to keep track of **code**, **data**, and **model**, but as well as the intermediate artifacts, things might become complicated soon. For example, when we conduct an ML experiment, we need to main the dependencies and keep track of the ETL pipeline as well. Also, random seed as well as documentation are miscellaneous, which might be hard to simpy categorize as data tracking due to its finer granularity. According to this paper(https://github.com/EthicalML/awesome-production-machine-learning/pull/293), I would suggest extending the scope a bit and renaming "model & data versioning" to "experiment tracking". @axsaucedo Any idea?

**Comment by zhimin-z** [comment]
> > Experiment reproducibility = model & data versioning, which is why it's suggested to include in that section
> 
> Honestly, I do not think this always holds for contemporary ML projects: Experiment reproducibility = model & data versioning.
> 
> Roughly, we need to keep track of **code**, **data**, and **model**, but this coarse granularity loses track of most of the non-trivial things in managing ML experiments since this view only focuses on artifacts from a **static** perspective. For example, when we conduct an ML experiment, we need to maintain optimizers (optimizer versioning), dependencies (dependency versioning) and keep track of the ETL pipeline (pipeline versioning) as well. Also, random seeds (seed versioning), documentation (observation versioning), and licenses (IP versioning) are miscellaneous, which might be hard to simply categorize as data tracking due to their finer granularity. Containerization indeed helps a lot which frees the MLOps engineers from versioning the hardware/OS-related things, but the model orchestration (schedule versioning) is another layer of complexity when conducting A/B deployment in the real world. When the drift (concept, data, etc.) happens, we also need to monitor the metrics/logs (log/metrics versioning) in case we need to retrain our model.
> 
> I would suggest extending the scope a bit and renaming "model & data versioning" to "experiment tracking", which makes more sense since most of the tools here (According to this paper in #293) are used for the latter purposes. I can also share my paper preprint on the terminology of ML experiment management in person later. Does that sound good so? @axsaucedo

Any comment, @axsaucedo
