### ISSUE TITLE
Move W&B from commercial section to open-source section

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#337]
W&B is free to use for personal and academic projects, it only charges fees if you use it for commercial purposes, just like HuggingFace. I'd suggest relocating W&B from commercial section to open-source section. @axsaucedo

**Comment by axsaucedo** [comment]
Closing as aligned - decision to keep on commercial

**Comment by zhimin-z** [comment]
> 

WandB is just like H2O, it has a commercial side but its main tool is still open-source. If we keep them in the commercial area, then we also need to relocate Pachyderm, CML, etc. to commercial section since they are charging fees for some services as well. @axsaucedo What do you think?

**Comment by axsaucedo** [comment]
This already has been discussed various times zhimin (in respective PR), wrappers to commercial platforms are not considered OSS unless they can work to its most extent. OSS that is freemium goes to commercial lists
