### ISSUE TITLE
New section on Generative AI

### ISSUE THREAD

**Issue by axsaucedo** [EthicalML/awesome-production-machine-learning#339]
With the growing pace of Generative AI models and tools I am wondering whether there could be a space to add a section on Generative AI in this section. It would be great to use this issue to brainstorm on what it could be, and identify whether we can find more than 5 relevant examples for production ML in context of Generative AI. Dalle-Flow is already a good example of a framework that could eb used as an example https://github.com/jina-ai/dalle-flow/.

**Comment by axsaucedo** [comment]
@zhimin-z it would be great to get your thoughts on this one

**Comment by zhimin-z** [comment]
> @zhimin-z it would be great to get your thoughts on this one

Thanks for invitation, @axsaucedo. Generative AI is definitely an awesome domain. Dalle-Flow is Human-in-the-Loop workflow for creating HD images from text, which correlates both industry-strength NLP as well as CV in our list. Also, I am thinking about integrating Dalle-Flow into Data Pipeline section. What do you think, @axsaucedo ?
<img width="689" alt="1676221238520" src="https://user-images.githubusercontent.com/8592144/218325337-b8e4b2b3-0528-40d2-add6-0473b6c5a615.png">

**Comment by axsaucedo** [comment]
Yes absolutely, I do think that would be the best suited area at this stage, but I would like to see if we can find a list of tools like dall-e flow for various Generative AI usecases, namely to see if these could all fit under their own "Industrial Generative AI" section, or whether we would just add them into the respective existing ones.

**Comment by zhimin-z** [comment]
> Yes absolutely, I do think that would be the best suited area at this stage, but I would like to see if we can find a list of tools like dall-e flow for various Generative AI usecases, namely to see if these could all fit under their own "Industrial Generative AI" section, or whether we would just add them into the respective existing ones.

Also, I wonder if we should add commercial tools like [jasper.ai](https://www.jasper.ai/) (as a Generative AI platform), this is becoming super popular and helpful these days. @axsaucedo

**Comment by zhimin-z** [comment]
Also, the pull request on generated data serving tools such as https://github.com/EthicalML/awesome-production-machine-learning/pull/340, where shall I put in the list?

**Comment by axsaucedo** [comment]
> Also, I wonder if we could add commercial tools like [jasper.ai](https://www.jasper.ai/) and [alexsei](https://www.alexsei.com/) (as production-level Generative AI platforms), this is becoming super popular and impactful these days. @axsaucedo

At this stage I would be keen to prioritise OSS tools in this issue, once we explore this we could have a look at commercial tools

**Comment by axsaucedo** [comment]
Here is another project that seems quite promising https://github.com/LAION-AI/Open-Assistant

**Comment by zhimin-z** [comment]
![image](https://user-images.githubusercontent.com/8592144/222870223-9fae9d5a-b19f-4b0b-920e-92836574da97.png)

An exclusive Generative AI section seems to touch too many tools (~100), wondering if it is better to split the toolchain into their respective parts (like we did right now). @axsaucedo

**Comment by zhimin-z** [comment]
Interesting, I search over the Internet and found there already exists two similar lists for generative AI:

- https://github.com/steven2358/awesome-generative-ai

- https://github.com/filipecalegario/awesome-generative-ai

**Comment by al-yakubovich** [comment]
One more list:
[https://github.com/meetpateltech/AI-Infinity](https://github.com/meetpateltech/AI-Infinity)

Maybe we can select only open source tools from those?

**Comment by zhimin-z** [comment]
Is there a standard when we regard the prompt engineering section as an individual? @axsaucedo

**Comment by axsaucedo** [comment]
The more the field of prompt engineering is defined the less I see it as relevant to this production list, I agree it's an important domain but it's high level in user interaction level to see it as relevant for this list, so I will close #424 as most of these are very high level tools to manage "text templates" which I don't see relevant.

**Comment by axsaucedo** [comment]
I would still be keen to continue exploring whether Generative AI tools can fall into a separate theme, and one area that I am seeing as potentially relevant is the area that I am currently referring to as "agent-chain architecture frameworks", which provide the infrastructure and tooling to augment LLMs through agents, chains, etc - the primary example of this of course is https://github.com/hwchase17/langchain (https://www.youtube.com/watch?v=nMniwlGyX-c). I would be open to exploring what a list of this "agent-chain architecture tooling" could look like, but I also want to be careful as I am conscious that there are some tools that can mask themselves as tooling infra but they really are just a "good-looking" front-end interfaces to LLMs.

**Comment by zhimin-z** [comment]
> I would still be keen to continue exploring whether Generative AI tools can fall into a separate theme, and one area that I am seeing as potentially relevant is the area that I am currently referring to as "agent-chain architecture frameworks", which provide the infrastructure and tooling to augment LLMs through agents, chains, etc - the primary example of this of course is https://github.com/hwchase17/langchain (https://www.youtube.com/watch?v=nMniwlGyX-c). I would be open to exploring what a list of this "agent-chain architecture tooling" could look like, but I also want to be careful as I am conscious that there are some tools that can mask themselves as tooling infra but they really are just a "good-looking" front-end interfaces to LLMs.

There is a core question: generative ai concerns many aspects such as NLP, CV, RL, etc. How could we distinguish one from another? If we do not set up a standard about what is generative ai compared to the other ML-specific domain, then it is hard to categorize tools.

**Comment by zhimin-z** [comment]
Also, generative ai is commonly used in everyday life rather than research or industry. Scientists or ML engineers specialize in NLP, RL, or CV, we seldom heard that "I am a specialist in generative ai."
