### ISSUE TITLE
Creating github action to perform automated releases 

### ISSUE THREAD

**Issue by axsaucedo** [EthicalML/awesome-production-machine-learning#353]
Creating issue following discussions with @zhimin-z on #324 proposal.

This encompasses a github action that performs releases every week / month, namely a workflow with:

* Tagging date / week
* Changelog generator
* Convert MD to PDF with pandoc
* Create release
* Attach changelog and PDF to release
* Publish release

This would be a high priority as it would make such a difference.

**Comment by zhimin-z** [comment]
We need to change the action name to let the release work. https://github.com/EthicalML/awesome-production-machine-learning/pull/390

**Comment by axsaucedo** [comment]
Closed via #357

**Comment by axsaucedo** [comment]
@zhimin-z this is done for security reasons, you can now find the forks in the EthicalML org as best practice to avoid injection of malicious code (which is why the action works atm) - this repo also has protection to avoid running external github actions
