### ISSUE TITLE
might need to remove modeldb

### ISSUE THREAD

**Issue by ryandawsonuk** [EthicalML/awesome-production-machine-learning#36]
See https://github.com/mitdbg/modeldb/issues/290#issuecomment-560344435

**Comment by axsaucedo** [comment]
Oh nice one! Good point - it seems they are still figuring out where it will be going so for now can leave it, but will leave this issue open. (cc @mpvartak)

**Comment by axsaucedo** [comment]
It seems link has been updated into VertaAI

**Comment by mpvartak** [comment]
Hi @ryandawsonuk and @axsaucedo ,

We are continuing development at https://github.com/VertaAI/modeldb and just released a new version! Let us know what you think.

Manasi
