### ISSUE TITLE
[Request] Add cmd_queue to data pipeline

### ISSUE THREAD

**Issue by Erotemic** [EthicalML/awesome-production-machine-learning#363]
I've written a pipelining tool called "cmd_queue" that I find incredibly useful over existing solutions in a particular niche: where you want to run a DAG of bash scripts. 

The package itself is mostly a frontend to existing pipeline tools. It can submit your bash jobs as airflow or slurm jobs, but unlike those tools it has fallbacks if those more heavy-weight systems are not installed on your machine.

At it's most basic, it has a "serial" mode where it runs your bash jobs sequentially. This means you can always at least run a pipeline no matter what machine you are on.

Slightly more advanced is a custom "tmux scheduler", where it does nearly the same thing as the "serial" mode, but it divides your jobs amongst several tmux sessions in such a way that the order of execution satisfies dependencies. This is very similar to how I would run a bunch of jobs manually if I didn't have any access to a scheduling tool, and it's only dependency is tmux, so no heavyweight slurm configs. This also means jobs are very introspectable, because they are just running in tmux. You can attach and watch them run in real time.

This is still a new package, but within its niche I think it compares well against its competition.

https://gitlab.kitware.com/computer-vision/cmd_queue

**Comment by zhimin-z** [comment]
@Erotemic Thanks for your contribution. However, I do not think this tool aligns well with production-level machine learning due to the following reasons:
1. This tool is not specifically designed for machine learning, I've checked this tool usage and found we can deploy such a tool in regular DevOps rather than MLOps only.
2. The stars are less than 100 levels ([minimum standard](https://github.com/EthicalML/awesome-production-machine-learning/blob/master/CONTRIBUTING.md)). We only include popular tools in the list due to the space.

**Comment by Erotemic** [comment]
Ah, you might want to take airflow / argo / luigi of the list then if point 1 is an issue. 

Point 2 makes sense. I suppose I'll ping agin when / if the package becomes more popular.

**Comment by zhimin-z** [comment]
> Ah, you might want to take airflow / argo / luigi of the list then if point 1 is an issue.
> 
> Point 2 makes sense. I suppose I'll ping agin when / if the package becomes more popular.

Speaking of devil, I think it is better to remove airflow / argo / luigi as well since they are quite general tools rather than ML or date-driven specific tools.

**Comment by Erotemic** [comment]
I did build it specifically for an ML use-case. I was unhappy with how much boilerplate and heavyweight tooling you needed to get airflow / slurm to execute a DAG of bash jobs (different prediction / evaluation / visualiztion steps of an ML pipeline). I wanted something that could leverage those more powerful tools when they are available, but would always have a simple parallel scheduler to fallback on (my custom tmux scheduler), and the option of running all jobs sequentially if all else failed.

Granted, the package certainly isn't well known or popular yet. I was attempting to increase its visibility by listing it here, but its understandable if that's not an appropriate use. It makes sense you would want this to expose people to well known tools, and not be an advertising platform for tools that could have potential.

**Comment by axsaucedo** [comment]
Completely correct from @zhimin-z reasoning on this one. In regards to Airflow and luigi, these tools are too much widely used and adopted by large organisations for ML so definitely an important one for produciton ML (I've seen more than the ones adopting ML specific ones)
