### ISSUE TITLE
Proposal to increase the tool bar for the list

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#383]
I recommend lifting the bar of the tools due to the bloating number of tools (~471) nowadays. We lift the bars and only keep the more impactful tools on our list since I notice a great number of tools (~13%) in our list are becoming unmaintained for several years (Of course, their repos' stars stop growing as well).

How about lifting the minimum requirements in terms of Git repo stars up to **500**?

_Why 500 stars rather than 300, or 200?_ 

**Empirically**, I notice a great sum of tools are losing popularity and eventually becoming obsolete (or unmaintained) before they reach the ceiling of 500 stars.

What do you think? @axsaucedo

**Comment by zhimin-z** [comment]
Also, there exist some tools that show up many times in the list:
![image](https://user-images.githubusercontent.com/8592144/222879967-b58aadb8-8476-4ded-b075-ab416857c7cc.png)

**Comment by axsaucedo** [comment]
This is a really good idea, and I do like the concept, however there's a couple of poits discussed, answering each:
* Duplicates = yes let's definitely remove - we can have a separate issue to ensure we address that one, good find!
* Raising the number of stars - that's an interesting suggestion, and I definitely see where you are coming from
    * I do agree that 100 stars are quite low, I do also find that stars are an important metric but not the only one
    * I would certainly be keen to revisit the guidelines to see what we could raise the bar on
    * I also wonder if we could think of a way to automatically validate this (ie do a quick automated check once we merge the release PR)

**Comment by zhimin-z** [comment]
> * I also wonder if we could think of a way to automatically validate this (ie do a quick automated check once we merge the release PR)

Thanks for your feedback. I wonder what it means to automatically validate this (ie do a quick automated check once we merge the release PR)? What do you have in mind? @axsaucedo

**Comment by zhimin-z** [comment]
> This is a really good idea, and I do like the concept, however there's a couple of poits discussed, answering each:
> 
> * Duplicates = yes let's definitely remove - we can have a separate issue to ensure we address that one, good find!
> * Raising the number of stars - that's an interesting suggestion, and I definitely see where you are coming from
>   
>   * I do agree that 100 stars are quite low, I do also find that stars are an important metric but not the only one
>   * I would certainly be keen to revisit the guidelines to see what we could raise the bar on
>   * I also wonder if we could think of a way to automatically validate this (ie do a quick automated check once we merge the release PR)

I know using the repo stars is not the best way to differentiate impactful vs unimpactful tools but this is perhaps the easiest and most efficient way to achieve so. Considering the fast-changing industry of ML tools, it might eventually become one of the most appropriate ways to decide whether or not to include a tool. Do you agree, @axsaucedo ?

**Comment by zhimin-z** [comment]
> 

Ok, can we try with 250 stars at this moment? @axsaucedo I can make a PR out of this talk accordingly.

**Comment by zhimin-z** [comment]
How about the update? If a tool has not been updated for one, or two years, shall we still keep it on our list? @axsaucedo

**Comment by zhimin-z** [comment]
> I don't see why not increasing it at least slightly, to 200 or 300, let's give it a try by this amount, I do agree that it's a good heuristic

The core logic why we need to set up a high bar (>500) rather than a medium one (>200, or 300) is that: if an OSS tool is used for production-level ML, then it definitely always draws enough attention from the industry. If not, we perhaps need to reevaluate this tool since not so many people pay attention (namely use) this tool in the real-world practices. Thus, I still recommend a high bar rather than a medium one. @axsaucedo
