### ISSUE TITLE
Proposal to retire the obsolete tags and releases

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#384]
SInce https://github.com/EthicalML/awesome-production-machine-learning/pull/357 comes out and automatic release becomes no problem, I wonder if it is good time to retire and remove those obsolete tags/releases in https://github.com/EthicalML/awesome-production-machine-learning/releases?

**Comment by axsaucedo** [comment]
Thank you @zhimin-z , it's not common practice to remove old releases as they are still relevant from older cycles, so makes sense to leave, but the automated ones will definitely provide much more up-to-date information
