### ISSUE TITLE
Proposal to make the categorization standard explicit and clear

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#387]
I found a great number of tools that span multiple categories and might not easily fall into one category, as can be seen from the talk https://github.com/EthicalML/awesome-production-machine-learning/pull/379.

Shall we further refine why a tool falls into a specific category rather than another? If a tool is designed for NLP tasks but its only functionality is computation optimization, shall we categorize this tool as an industry-strength tool or a computation optimization tool?

**Comment by axsaucedo** [comment]
Closing as per #392
