### ISSUE TITLE
Proposal to remove _config.yml

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#389]
As is noticed in https://github.com/EthicalML/awesome-production-machine-learning/pull/382, there does not seem to be any difference after removing it.

**Comment by axsaucedo** [comment]
This is for the github pages theme https://ethicalml.github.io/awesome-production-machine-learning

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll
