### ISSUE TITLE
Proposal for reviewing issues first and then critiquing PR.

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#393]
I found it confusing that the PRs get criticized first and a lot of discussion of similar issues are talked about over and over again. However, a lot of open issues are ignored for quite a while but they are actually related to the criticized PRs. 

I propose to discuss fully the open issues first and then review the PRs before making a decision to close/modify it. @axsaucedo

**Comment by axsaucedo** [comment]
Closing as per #392

**Comment by zhimin-z** [comment]
> Closing as per #392

This is a separate issue which is not related to https://github.com/EthicalML/awesome-production-machine-learning/issues/392 

Why do you close it? @axsaucedo
