### ISSUE TITLE
Proposal for better guideline of commitment and merge

### ISSUE THREAD

**Issue by zhimin-z** [EthicalML/awesome-production-machine-learning#394]
Continuing https://github.com/EthicalML/awesome-production-machine-learning/issues/392, we should make up a more concrete guideline to solve the following issues:

- What is the goal of this list?
- What categories of tools can be included in this list?
- What are the categorization criteria when a tool is designed with multi-purposes?
- What is the retirement mechanism to remove obsolete tools?
- ...

It is useless to simply avoid superficial problems such as [3 line PRs resulting in a discussion 10x longer](https://github.com/EthicalML/awesome-production-machine-learning/pull/379). We need to work together to solve the core contradiction for better collaboration.

**Comment by axsaucedo** [comment]
Closing as discussed in #392 - reached out to align but further discussion won't proceed otherwise as clarified

**Comment by zhimin-z** [comment]
> Closing as discussed in #392 - reached out to align but further discussion won't proceed otherwise as clarified

The current contribute.md did not solve any of the issues mentioned above. @axsaucedo Why are you avoiding the core issues?

**Comment by zhimin-z** [comment]
I have checked your website: https://ethical.institute/ and this gives a detail explanation regarding the guideline of Ethical AI & Machine Learning, why do you prevent me to talk about the guideline regarding this list? @axsaucedo

**Comment by axsaucedo** [comment]
It's been explained over and over Zhimin, unfortunately I don't have the time or energy to entretain this as it seems it's repeating the same point over and over. I reached out to discuss further to align but we can't continue going in circles as the reasonings have been discussed over and over.

**Comment by zhimin-z** [comment]
> #392

@axsaucedo I 've read every word of your reply. 
![image](https://user-images.githubusercontent.com/8592144/223813803-db584b43-68c0-485f-8b83-a3eb5711c32e.png)
![image](https://user-images.githubusercontent.com/8592144/223814582-ddf56895-6ce9-4ffc-8c4b-1f764dfed325.png)

I had never said "there should be an exact definition that everyone should agree." I say that we should at least to have a template definition to refer to which helps us to reach a concensus. I am 100% sure now what's on your mind of "production machine learning" is different from that on my mind. But sadly, I have no idea what the difference is. I have to guess and you always close my pr due to my wrong guess. 

For example, as a researcher, when you are talking about something in the publication, you usually at first give some background info and define the old concepts before you are going to introduce the new ones, **or else** the reviewers won't have the same start point as your mind, resulting a lot of misunderstanding and rebuttal. @axsaucedo You understand what I mean?
