### ISSUE TITLE
Suggest to add Substra framework to Model Deployment and Orchestration Frameworks

### ISSUE THREAD

**Issue by ClementMayer** [EthicalML/awesome-production-machine-learning#48]
Hello, 

I would like to present Substra: an open-source framework for privacy-preserving, traceable and collaborative Machine Learning.

Substra gathers data providers and algorithm designers into a network of nodes that can train models on demand but under advanced permission regimes. To guarantee data privacy, Substra implements distributed learning: the data never leave their nodes; only algorithms, predictive models and non-sensitive metadata are exchanged on the network. The computations are orchestrated by a Distributed Ledger Technology which guarantees traceability and authenticity of information without needing to trust a third party. Although originally developed for Healthcare applications, Substra is not data, algorithm or programming language specific. It supports many types of computation plans including parallel computation plan commonly used in Federated Learning. With appropriate guidelines, it can be deployed for numerous Machine Learning use-cases with data or algorithm providers where trust is limited. 

- Whitepaper: https://arxiv.org/abs/1910.11567

Github: 

- Substra Foundation: https://github.com/SubstraFoundation/welcome

- Framework: https://github.com/SubstraFoundation/substra

**Comment by axsaucedo** [comment]
Great - would you be able to add it as PR?

**Comment by ClementMayer** [comment]
Hello, Yes I have added a pull request. 
I finally set on "Privacy preserving machine learning" as I think it fits best.
Let me know if any additional information is needed
