### ISSUE TITLE
Documenting non-maintained repos under a GRAVEYARD.md

### ISSUE THREAD

**Issue by axsaucedo** [EthicalML/awesome-production-machine-learning#531]
Following https://github.com/EthicalML/awesome-production-machine-learning/pull/520 creating an issue to document comment:

It could be worth to somehow keep a list of "REMOVED", perhaps it could go into a "GRAVEYARD.md" eventually, as in a way it could be useful both for reference, but also as a link for the CONTRIBUTING.md. Similarly it would be useful to keep this script in the repo, could you add it? Perhaps under `scripts/`. That way we can also explore eventually automating this. + also documenting in the CONTRIBUTING.md that this script is run (every month)

**Comment by zhimin-z** [comment]
> Following #520 creating an issue to document comment:
> 
> It could be worth to somehow keep a list of "REMOVED", perhaps it could go into a "GRAVEYARD.md" eventually, as in a way it could be useful both for reference, but also as a link for the CONTRIBUTING.md. Similarly it would be useful to keep this script in the repo, could you add it? Perhaps under `scripts/`. That way we can also explore eventually automating this. + also documenting in the CONTRIBUTING.md that this script is run (every month)

Hi, that might be a good idea. However, we have a release list that holds all tool lists in history. Check [here](https://github.com/EthicalML/awesome-production-machine-learning/releases)
