### ISSUE TITLE
Where to add mindspore?

### ISSUE THREAD

**Issue by fkromer** [EthicalML/awesome-production-machine-learning#65]
HUAWEI recently open sourced [MindSpore](https://e.huawei.com/en/products/cloud-computing-dc/atlas/mindspore) ([github - mindspore-ai/mindspore](https://github.com/mindspore-ai/mindspore)). I'd consider it an open source end-to-end platform. Into which section should it be put?

**Comment by axsaucedo** [comment]
Interesting - we now have a section on ML Inference and Deployment, so this sems like it would fit on that one

**Comment by axsaucedo** [comment]
Closing as no response but do add a PR if possible
