### ISSUE TITLE
Create new section commercial e2e platforms

### ISSUE THREAD

**Issue by fkromer** [EthicalML/awesome-production-machine-learning#69]
The commercial platforms section may be miss-leading. Often it's not obvious if the platforms are end-to-end platforms with more less "complete" feature set (e.g. dataiku DSS) or commercial variants of single components of an overall e2e platform, like e.g. experiment management (e.g. neptune.ai) or model deployment (e.g. datatron). For new contributors it would be helpful to have a separate end-to-end ml platform section.

**Comment by axsaucedo** [comment]
That is a good point @fkromer, the core objective when creating this list was to highlight open source projects, and was not intended to showcase vendors, hence why we haven't really categorized the commercial platforms list. 

Saying this out-loud I think it may be best if we remove the commercial platforms section to avoid this ambiguity.

**Comment by fkromer** [comment]
My main point of confusion was that "platform" implied "end-to-end (e2e)" for me. The commercial section was helpful nevertheless because it gives you references where you can find out what features you would like to have over the long run even when building an own e2e platform consisting of open source e2e platforms and/or components from the other sections. I'd keep the commercial platforms section cause I considered it valuable. Probably it's better to state per entry if the SW is open source, commercial or both like other awesome lists do.

**Comment by axsaucedo** [comment]
Ok awesome, let's leave it there for now, and maybe as it grows it could be broken down further in the medium term.
