### ISSUE TITLE
PRs Add Descriptions

### ISSUE THREAD

**Issue by axsaucedo** [EthicalML/awesome-production-machine-learning#84]
Massive thanks for all the additions @fkromer ! Really great finds! Only thing before we can merge teh PRs, would be to add a short rescription to all the libraries in #83, #82, #81, #80, #79, #78, #77, #76, #75 and #74 - let me know if you can add those, if not I can also jump in and add descriptions.

**Comment by fkromer** [comment]
@axsaucedo Would be great if you could help out. I won't be able to add descriptions soon.

**Comment by fkromer** [comment]
@axsaucedo A description is added to #75, #83, #80, #79, #76.

**Comment by axsaucedo** [comment]
Awesome - thank you! I've landed those, thank you for adding descriptions!

**Comment by fkromer** [comment]
@axsaucedo Your are welcome. I'll let you know in case I'll find time to add other missing descriptions as well.

**Comment by axsaucedo** [comment]
@fkromer thanks again for the previous contributions, I've removed the inactive PRS, but will be keeping this issue open for when they can be readded with descriptions
