### ISSUE TITLE
Bonobo is worth mentioning in ETL

### ISSUE THREAD

**Issue by hexerei** [EthicalML/awesome-production-machine-learning#92]
Not necessarily for big data projects, but for Adhoc machine learning ETL-ing and especially for its ease-of-use it should find its place in your list:

https://www.bonobo-project.org/
http://docs.bonobo-project.org/en/master/
https://github.com/python-bonobo/bonobo

**Comment by axsaucedo** [comment]
Definitely, sounds good! @hexerei would you be able to add a PR with this?

**Comment by hexerei** [comment]
added pull request today, sorry for the delay, you caught me on vacation :)
