### ISSUE TITLE
Explore potential section on ML monitoring (or potential subsets such as outlier/anomaly detection / concept drift, etc)

### ISSUE THREAD

**Issue by rmminusrslash** [EthicalML/awesome-production-machine-learning#94]
I was wondering if it could be useful to open a section on production (serving, ml specific monitoring of the model and the data distributions)?

**Comment by axsaucedo** [comment]
Interesting. Yeah I think this is a good idea for Serving actually, there's now enough tools in this space to have it's own section. For monitoring I'm not sure, what are the tools that would go in the monitoring section?

**Comment by visenger** [comment]
@axsaucedo I think, we could start with Prometheus and the ELK Stack (Elasticsearch, Logstash, and Kibana)

**Comment by axsaucedo** [comment]
I like the idea of adding monitoring, although I am not sure about linking generic frameworks without the direct specialisation to ML. Let's update this issue to make it focused on identifying specialised open source model monitoring projects, it may be that we could add a more specific section, such as "outlier/anomaly detectors" or "concept drift" - having said that if there are sub-projects from ELK or prometheus that focus on ML, or implemenations that perform ML then we would be able to create a section. What are your thoughts on this?

**Comment by axsaucedo** [comment]
I will add a disjoint issue to add a section on ML serving frameworks

**Comment by rmminusrslash** [comment]
we can start with having a section on serving and add serving and monitoring tools there. If it becomes too big, we split. I propose to only add ML specific tools. TFX by tensorflow is one candidate for monitoring, e.g. 

`Distribution Skew occurs when the distribution of feature values for training data is significantly different from serving data. `
https://www.tensorflow.org/tfx/guide/tfdv#training-serving_skew_detection

**Comment by axsaucedo** [comment]
That's a good idea, both on starting first with a section on serving, and on adding tfx - although that one would fall under the serving as most serving tools would include monitoring. In that case let's explore #98 and come back to this one, I'll leave the issue open so we can coninue sharing tools in monitoring

**Comment by momegas** [comment]
Here is also a project in its infancy that has to do with model monitoring.
[Whitebox](https://github.com/squaredev-io/whitebox)
