### ISSUE TITLE
Add new section on ML Serving

### ISSUE THREAD

**Issue by axsaucedo** [EthicalML/awesome-production-machine-learning#98]
As suggested and discussed in #94 with @rmminusrslash and @visenger  we'll add a new section on ML serving, as there's been quite a lot of new projects in this space. A few ML Serving frameworks include:

* Seldon Core
* KFServing
* BentoML
* Cortex
* TFX
* TFSerivng
* ForestFlow

Any other suggestions? @rmminusrslash / @visenger  would you be interested on explore adding a PR?

**Comment by rmminusrslash** [comment]
sure, would be happy to, can make on the weekend. If you want to do it earlier, go ahead.

There are a few more
TFX serving
Sagemaker

**Comment by axsaucedo** [comment]
Good idea on tfx serving - but sagemarker is not OSS

**Comment by axsaucedo** [comment]
One more to add
* ForestFlow

**Comment by axsaucedo** [comment]
Thanks @rmminusrslash - that would be awesome! Let me know if you need a hand on anything, only thing required would be to keep format and add alphabetical. If you can do it before Sunday I'd be keen to give you a shoutout on our weekly newsletter (if you want ofc, happy to just mention a new section has been added otherwise)

**Comment by visenger** [comment]
@axsaucedo and @rmminusrslash 
The [alibi-detect](https://docs.seldon.io/projects/alibi-detect/en/stable/index.html) library includes **concept drift detection** functionality. What do you think, would it be suitable for the monitoring section?

**Comment by axsaucedo** [comment]
Thank you @visenger ! I actually think we could explore adding a section specifically on "outlier / anomaly detection" and potentially concept drift - primarily as otherwise monitoring could be quite broad. It would be the same challenge with explainability, as in theory you could also use XAI algorithms in context of monitoring. I would be quite keen to add a section on outlier/anomaly detection tho! @visenger is this something that you'd be interested? We could try to explore this on a separate issue similar to #94

**Comment by visenger** [comment]
@axsaucedo Yes, I think adding a separate section on outlier/anomaly detection for ml models is a good idea. Also, “Model Governance” is another candidate for a separate section.

**Comment by axsaucedo** [comment]
@visenger I completely agree, I think the ecosystem has grown enough to find quite a lot of tools in the anomaly/outlier detection space, I'll add a new issue where we can find / identify tools and then add a section.

In regards to the model governance, I completely agree that it's a critical piece in the MLOps space, however I am of the same mindset as with Monitoring - model governance consists of quite a broad set of sub-components. And although I am quite keen to add some of those sub-components as lists, I don't think there are enough tools yet (althoguh I'm sure in 6 months this will probably change). Examples of sub-components of model governance include model databases, model metadata stores, model policy/rule engines for compliance, etc.

**Comment by axsaucedo** [comment]
@visenger I completely agree, I think the ecosystem has grown enough to find quite a lot of tools in the anomaly/outlier detection space, I'll add a new issue where we can find / identify tools and then add a section.

In regards to the model governance, I completely agree that it's a critical piece in the MLOps space, however I am of the same mindset as with Monitoring - model governance consists of quite a broad set of sub-components. And although I am quite keen to add some of those sub-components as lists, I don't think there are enough tools yet (althoguh I'm sure in 6 months this will probably change). Examples of sub-components of model governance include model databases, model metadata stores, model policy/rule engines for compliance, etc.

**Comment by rmminusrslash** [comment]
I made a branch but get a permission error when pushing:
```git push --set-upstream origin add-serving-section
^[[O^[[I^[[O^[[Iremote: Permission to EthicalML/awesome-production-machine-learning.git denied to rmminusrslash.
fatal: unable to access 'https://github.com/EthicalML/awesome-production-machine-learning.git/': The requested URL returned error: 403
```

@axsaucedo On reviewing the section on model orchestration and deployment it's not clear what to migrate. Many orchestration tools seems to cover multiple parts of the live cycle. Shall we keep those in "orchestration" and only move pure serving tools?

**Comment by axsaucedo** [comment]
@rmminusrslash fantastic! You need to first fork the repo, which would create a copy under your account. You would then push your branch to that repo and will then be able to submit the PR from that repo/branch.

In regards to your second question, I think for now probably best would be to just remove the tools that are being added into the serving section (which are currently in the orchestration section)

**Comment by axsaucedo** [comment]
@rmminusrslash did you manage to fork the repo? Let me know if you have issues and we can explore other ways

**Comment by rmminusrslash** [comment]
done! sorry, was busy with a conference talk for today.

**Comment by axsaucedo** [comment]
No worries @rmminusrslash, hope it went well. PR looks great, I added a couple of comments
