### ISSUE TITLE
Add new section on outlier detection

### ISSUE THREAD

**Issue by axsaucedo** [EthicalML/awesome-production-machine-learning#99]
As discussed in #98 with @visenger , we'll explore adding a new section on outlier detectors, some outlier detection libraries identified include:
* https://github.com/SeldonIO/alibi-detect
* https://github.com/yzhao062/pyod
* https://github.com/yzhao062/SUOD
* https://github.com/hendrycks/outlier-exposure

I excluded libraries with less than 100 stars. If we can identify a couple more these should be enough for a new section.

**Comment by axsaucedo** [comment]
@visenger would you be interested on explore adding a PR for the outlier detection frameworks?

**Comment by visenger** [comment]
@axsaucedo Yes, sure. Probably will come to this task over this weekend.

**Comment by axsaucedo** [comment]
Awesome, sounds great @visenger thanks for the support!

**Comment by visenger** [comment]
@axsaucedo I found four more libraries for outlier/anomaly detection, so in total there are 8 repositories.

**Comment by axsaucedo** [comment]
This is fantastic @visenger - dBoost seems to be on the shorter side on the popularity (ie stars) however given you've used it and have good things to say keen to add it. Sounds perfect! Would you be able to submit a PR with these? I think 8 would be an absolutely fantastic contribution! If we can add it today I'd be really keen to announce it in the nwesletter and give you a shoutout (if you are happy with that of course)

**Comment by visenger** [comment]
@axsaucedo Sounds good! Yes, I could do this today.

**Comment by visenger** [comment]
@axsaucedo done! 
You can mention me as Larysa Visengeriyeva (@visenger)
Have a great day!

**Comment by axsaucedo** [comment]
Sounds perfect @visenger ! PR looks great! Added a small comment but other than that should be good to go!

**Comment by axsaucedo** [comment]
Closed by #100 - thanks @visenger !
